export const CHECK_ADDRESS = 'CHECK_ADDRESS';
export const CHECK_ADDRESS_START = 'CHECK_ADDRESS_START';
export const CHECK_ADDRESS_SUCCESS = 'CHECK_ADDRESS_SUCCESS';
export const CHECK_ADDRESS_FAIL = 'CHECK_ADDRESS_FAIL';
export const CHECK_ADDRESS_COMPLETE = 'CHECK_ADDRESS_COMPLETE';

export const GET_WEB3_CONTRACT = 'GET_WEB3_CONTRACT';
export const SET_WEB3_CONTRACT = 'SET_WEB3_CONTRACT';